version: "3.4"
services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce
        ports:
            - "8011:80"
        restart: "always"
        depends_on:
            - nopcommerce_database
    nopcommerce_database:
        image: "postgres:latest"
        container_name: nopcommerce_postgres_server
        ports:
            - "5432:5432"
        restart: "always"
        environment:
          POSTGRES_PASSWORD: "nop_db@10d"

volumes:
  nopcommerce_data: